# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "thin", "~> 1.8"

gem "puma", "~> 5.6"

gem "reel", "~> 0.6.1"

gem "http", "~> 5.0"

gem "webrick", "~> 1.7"

gem "pg", "~> 1.3"
