let a=name1.value.toLowerCase(); 
let b=name2.value.toLowerCase();
  if(a!=''&&b!='');
  for(i=0;i<a.length;i++){
  for(j=0;j<b.length;j++){
   {
     if(a[i]==b[j])
       a=replaceAt(a[i],'*');
       b=replaceAt(b[j],'*');
   }   
}
  }
    let count=0;
    for(i=0;i<a.length;i++){
        if(a!='*')
        count++;
        
    }
    for(i=0;i<b.length;j++)
        {
            if(b!='*')
            count++;
        }
     const input=FLAMES;
         c=0;
         l=1;
        if(count!=0)
        {
          for(k=0;k<input.length;k--)
             if(l==count){
                 if(c>=input.length){
                     c=0;
                 }
               flames=replaceAt(flames,c,'')
               if(c>=input.length)
               {
                   c=0;
               }  
               c++;
               l++;
             }         
    switch(flames)
    {
        case'F':
          {
              console.log('friend');
          }
        case'L':
        {
            console.log('Love')
        }  
        case'A':
        {
            console.log('Affection');
        }
        case'M':
        {
            console.log('Maariage');
        }
        case'E':
        {
            console.log('enemy');
        }
        case'S':
        {
            console.log('Sister');
        }
    }
        }