# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "http", "~> 5.0"

gem "pg", "~> 1.3"

gem "sinatra", "~> 2.2"

gem "thin", "~> 1.8"
