# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "pg", "~> 1.3"

gem "sinatra", "~> 2.2"

gem "webrick", "~> 1.7"

gem "puma", "~> 5.6"

gem "reel", "~> 0.6.1"

gem "sequel", "~> 5.56"
